//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int ID { get; set; }
        public int UserRole { get; set; }
        public int UserAction { get; set; }
    
        public virtual UserAction UserAction1 { get; set; }
        public virtual UserRole UserRole1 { get; set; }
    }
}
